//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sportProductsApp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PickPoints
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PickPoints()
        {
            this.Order = new HashSet<Order>();
        }
    
        public int Id { get; set; }
        public int Id_index { get; set; }
        public int Id_city { get; set; }
        public int Id_street { get; set; }
        public Nullable<int> HouseNum { get; set; }
    
        public virtual Cities Cities { get; set; }
        public virtual Indexes Indexes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Order { get; set; }
        public virtual Streets Streets { get; set; }
    }
}
